data_setting:
    "num_col_names": [
        "battery_power", 
        "clock_speed", 
        "int_memory", 
        "m_dep",
        "mobile_wt", 
        "px_height",
        "px_width",
        "ram",
        "sc_h",
        "sc_w",
        "talk_time",
    ]
    "cat_col_names": [
        "blue", 
        "dual_sim", 
        "fc", 
        "four_g", 
        "n_cores", 
        "pc", 
        "three_g",
        "touch_screen",
        "wifi",
    ]

model_setting:
    "target": ["price_range"]
    "n_splits": 5
    "shuffle": True
    "SEED": 1234